# Use an official lightweight Python image as the base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Update pip, setuptools, and wheel to avoid build issues
RUN pip install --upgrade pip setuptools wheel
# Install Tesseract OCR and its dependencies
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-eng \
    libtesseract-dev \
    && apt-get clean

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the Flask port
EXPOSE 5000

# Define environment variables
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV STORAGE_PATH=index
ENV FLASK_ENV=production

# Run the Flask app, bind it to 0.0.0.0 to make it accessible from outside the container
CMD ["python", "app.py", "--host=0.0.0.0", "--port=5000"]